---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.8.5
  deprecations_as_errors: true

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[custom_apache::default]
    attributes:
